### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by Hemedbz** [gventuri/pandas-ai#5] opened 2023-04-29 06:40 UTC
I saw on the TODO list that you'd like to add a CLI functionality, I'd like to do that, wanted to make sure it's okay before I start.

**Comment by gventuri** [comment] 2023-04-29 07:09
@Hemedbz sounds great! I've assigned the task to you 🚀

**Comment by Hemedbz** [comment] 2023-04-29 11:36
Great. thanks! Will update in a few days.

**Comment by gventuri** [comment] 2023-04-29 12:42
Looking forward for it!

**Comment by gventuri** [comment] 2023-05-06 23:06
Hey @Hemedbz, did you have a chance to have a look into it?

**Comment by Hemedbz** [comment] 2023-05-09 08:16
Hi, sorry it's been a busy week... Working on it, and writing to you maybe
we can schedule a zoom this weekend?

**Comment by gventuri** [comment] 2023-05-15 22:51
Closing, as it is a duplicate of #104. There is a PR for that (#107)

**Closed by gventuri** 2023-05-15 22:51 UTC
Labels: enhancement
