### ISSUE TITLE
Crash in conversational mode

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#81] opened 2023-05-07 19:35 UTC
### 🐛 Describe the bug

I load data from CSV file:

`df = pd.read_csv(dataFile, encoding='ISO-8859-1')`

This file has columns name, price, width and height.

I created pandasAI with  conversational = True:

```
pandas_ai = PandasAI(
    llm, 
    verbose = True, 
    conversational = True 
)
```

Some questions work fine:
- How many items you have with size less than 200x200? 
There are 18 items that have a size smaller than 200x200.
- How many rows?
There are 21 rows, did that answer your question?

But some questions return with crash.

How many chairs do you have?

```
File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    the next line of the prompt.

  File ["<ipython-input-45-508395eda1c3>"](https://localhost:8080/#), line 1, in <cell line: 1>
    pandas_ai.run(df, prompt='How many chairs have you?')

  File "/usr/local/lib/python3.10/dist-packages/pandasai/__init__.py", line 103, in run
    code = self._llm.generate_code(

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 117, in generate_code
    return self._extract_code(self.call(instruction, prompt))

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 91, in _extract_code
    code = self._polish_code(code)

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 60, in _polish_code
    self._remove_imports(code)

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 36, in _remove_imports
    tree = ast.parse(code)

  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,

  File "<unknown>", line 1
    <startCode>
    ^
SyntaxError: invalid syntax
```

I have $200. What I can buy?

```
File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    the next line of the prompt.

  File ["<ipython-input-38-77eb4102830b>"](https://localhost:8080/#), line 1, in <cell line: 1>
    pandas_ai.run(df, prompt='I have $200. What I can buy?')

  File "/usr/local/lib/python3.10/dist-packages/pandasai/__init__.py", line 103, in run
    code = self._llm.generate_code(

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 117, in generate_code
    return self._extract_code(self.call(instruction, prompt))

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 91, in _extract_code
    code = self._polish_code(code)

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 60, in _polish_code
    self._remove_imports(code)

  File "/usr/local/lib/python3.10/dist-packages/pandasai/llm/base.py", line 36, in _remove_imports
    tree = ast.parse(code)

  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,

  File "<unknown>", line 1
    <startCode>
    ^
SyntaxError: invalid syntax
```

**Comment by gventuri** [comment] 2023-05-07 20:49
@PavelAgurov thanks a lot for reporting.

The flag conversational (although I realize it's not a great naming), is actually meant to answer in a conversational way, so basically you don't get the factual response, but a more "conversational" response based on the facts.

Apart from that, would be helpful to know how your dataset is structured. For example, "how many chairs do you have" could be very misleading. Can you share a sample (anonymized) of the dataframe?

**Comment by PavelAgurov** [comment] 2023-05-08 19:57
@gventuri , sure, I have tested and compared conversation true and false.

I got dataframe from kaggle.

```
item_id,name,category,price,height,width
90420332,FREKVENS,Bar furniture,265,99,51
368814,NORDVIKEN,Bar furniture,995,105,80
49278341,BRIMNESE,Beds,895,110,96
89326463,PLATSA,Beds,2111,43,140
50468953,VATTVIKEN,Beds,995,86,92
59099136,BRIMNESA,Beds,795,111,146
19254209,SAGSTUA,Beds,545,140,148
20400691,BRIMNESB,Beds,575,47,96
30409295,KOLB–RN,Bookcases,345,81,80
60295706,MOSTORP,Bookcases,417,27,160
80385616,BILLY,Bookcases,516,202,80
90311069,OBSERV–R,Bookcases,15,18,30
79129081,EKTORP,Chairs,675,88,104
49304199,LEIFARNE,Chairs,195,87,52
211088,STEFAN,Chairs,85,90,42
50364149,ODGER,Chairs,177,81,45
217797,GUNDE,Chairs,30,78,41
19289303,DELAKTIG,Sofas,2350,79,94
19299726,VIMLE,Sofas,7765,83,349
29276965,VALLENTA,Sofas,4116,84,273
29277026,VALLENTB,Sofas,2300,84,186
```

As you can see my question was about count of items with defined category.
For many questions it works very good, but still I can find list of questions where it's crashed.

**Comment by sandiemann** [comment] 2023-05-15 22:12
@PavelAgurov I am not able to re-produce this. are you using the latest pandasai version. you can check by running,
`pip freeze | grep pandasai` and please try to upgrade to the latest version `pip install pandasai -U` (latest version v0.2.11) Since it could be related to the issues with parsing response as code.

Here's what I did:
```
import pandas as pd
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
data = [
    ['90420332', 'FREKVENS', 'Bar furniture', 265, 99, 51],
    ['368814', 'NORDVIKEN', 'Bar furniture', 995, 105, 80],
    ['49278341', 'BRIMNESE', 'Beds', 895, 110, 96],
    ['89326463', 'PLATSA', 'Beds', 2111, 43, 140],
    ['50468953', 'VATTVIKEN', 'Beds', 995, 86, 92],
    ['59099136', 'BRIMNESA', 'Beds', 795, 111, 146],
    ['19254209', 'SAGSTUA', 'Beds', 545, 140, 148],
    ['20400691', 'BRIMNESB', 'Beds', 575, 47, 96],
    ['30409295', 'KOLB–RN', 'Bookcases', 345, 81, 80],
    ['60295706', 'MOSTORP', 'Bookcases', 417, 27, 160],
    ['80385616', 'BILLY', 'Bookcases', 516, 202, 80],
    ['90311069', 'OBSERV–R', 'Bookcases', 15, 18, 30],
    ['79129081', 'EKTORP', 'Chairs', 675, 88, 104],
    ['49304199', 'LEIFARNE', 'Chairs', 195, 87, 52],
    ['211088', 'STEFAN', 'Chairs', 85, 90, 42],
    ['50364149', 'ODGER', 'Chairs', 177, 81, 45],
    ['217797', 'GUNDE', 'Chairs', 30, 78, 41],
    ['19289303', 'DELAKTIG', 'Sofas', 2350, 79, 94],
    ['19299726', 'VIMLE', 'Sofas', 7765, 83, 349],
    ['29276965', 'VALLENTA', 'Sofas', 4116, 84, 273],
    ['29277026', 'VALLENTB', 'Sofas', 2300, 84, 186]
]

columns = ['item_id', 'name', 'category', 'price', 'height', 'width']

df_new = pd.DataFrame(data, columns=columns)
llm = OpenAI()
pandas_ai = PandasAI(llm, verbose=True, conversational=True)
response = pandas_ai.run(df_new, "How many items you have with size less than 200x200?")
 
Running PandasAI with openai LLM...
Code generated:

df['size'] = df['height'].astype(int) * df['width'].astype(int)
count = len(df[df['size'] < 40000])
print(count)

Answer: 21
Conversational answer: There are 21 items that have a size smaller than 200x200.
How many chairs do you have?
```

- example 2:

```
response = pandas_ai.run(df_new, "How many chairs do you have?")
Running PandasAI with openai LLM...
Code generated:

df[df['category'] == 'Chairs'].shape[0]

Answer: 5
Conversational answer: "Oh, I have five chairs."
```

- example 3:

```
response = pandas_ai.run(df_new, "I have $200. What I can buy?")
Running PandasAI with openai LLM...
Code generated:

df['price'] = df['price'].astype(int)
affordable_items = df[df['price'] <= 200]
print(affordable_items[['name', 'category', 'price']])

Answer:         name   category  price
11  OBSERV–R  Bookcases     15
13  LEIFARNE     Chairs    195
14    STEFAN     Chairs     85
15     ODGER     Chairs    177
16     GUNDE     Chairs     30
```

**Comment by PavelAgurov** [comment] 2023-05-16 08:08
Sure, I will check with last version, my installed version is 0.2.2.

**Comment by PavelAgurov** [comment] 2023-05-16 21:44
Ok, last version is 0.2.12. It's much better, thanks!

But, let's see some other tests, if you don't mind.

First, I've uploaded data from file

`df = pd.read_csv('IKEA_small.csv', encoding='ISO-8859-1')`

I'm sure it's not critical, but just to have the same code as mine.

![image](https://github.com/gventuri/pandas-ai/assets/37487002/1e63a2fa-5276-4407-8a82-ba030de38532)

![image](https://github.com/gventuri/pandas-ai/assets/37487002/1fe9a6d3-1fb5-470c-9aa6-71bc6f4e74e8)

Fine. We have data. Let's check.

**pandas_ai.run(df, prompt='I want to buy a table')**

```
Running PandasAI with openai LLM...

Code generated:

import pandas as pd

# create dataframe
data = {'item_id': [49278341, 49278341, 89326463, 50468953, 89326463],
        'name': ['PLATSA', 'BRIMNESE', 'NORDVIKEN', 'VATTVIKEN', 'FREKVENS'],
        'category': ['Beds', 'Bar furniture', 'Beds', 'Bar furniture', 'Beds'],
        'price': ['995', '265', '995', '895', '2111'],
        'height': ['105', '110', '86', '105', '43'],
        'width': ['140', '51', '92', '92', '140']}

df = pd.DataFrame(data)

# filter for tables
table_df = df[df['category'].str.contains('Table')]

print(table_df)

Answer: Empty DataFrame
Columns: [item_id, name, category, price, height, width]
Index: []

Conversational answer: Sure, I can help you with that! Can you please provide me with some details about the table you are looking for? Such as the size, style, and budget? This will help me find the perfect table for you.
```

There are 2 questions here:
1. Can you check contains without case sensitive i.e. case=False?
2. If result is empty it seems we have no tables, so no reason to ask about details like size, budget...

**pandas_ai.run(df, prompt='I have $200. What I can buy?')**

```
Running PandasAI with openai LLM...

Code generated:

import pandas as pd

# create the dataframe
data = {'item_id': [50468953, 50468953, 368814, 90420332, 89326463],
        'name': ['BRIMNESE', 'FREKVENS', 'NORDVIKEN', 'VATTVIKEN', 'PLATSA'],
        'category': ['Beds', 'Beds', 'Bar furniture', 'Beds', 'Bar furniture'],
        'price': [995, 895, 895, 995, 265],
        'height': [105, 86, 43, 43, 86],
        'width': [140, 96, 92, 140, 92]}
df = pd.DataFrame(data)

# filter the dataframe based on the price
budget = 200
affordable_items = df[df['price'] <= budget]

# print the affordable items
print(affordable_items)

Answer: Empty DataFrame
Columns: [item_id, name, category, price, height, width]
Index: []

Conversational answer: I'm sorry, but I couldn't find any items that you can buy with $200.
```

It's correct for generated dataframe, but not correct for my dataframe. At least 2 rows have price less than 200.

**pandas_ai.run(df, prompt='What is the lowest price for a chair?')**

```
Running PandasAI with openai LLM...

Code generated:

import pandas as pd

# create dataframe
data = {'item_id': [49278341, 90420332, 50468953, 50468953, 89326463],
        'name': ['NORDVIKEN', 'FREKVENS', 'PLATSA', 'VATTVIKEN', 'BRIMNESE'],
        'category': ['Bar furniture', 'Beds', 'Bar furniture', 'Beds', 'Beds'],
        'price': [2111, 995, 995, 2111, 895],
        'height': [110, 86, 43, 86, 99],
        'width': [92, 51, 140, 92, 80]}
df = pd.DataFrame(data)

# find lowest price for chair
chair_prices = df[df['category'] == 'Chairs']['price']
lowest_price = chair_prices.min()

print(lowest_price)

Answer: nan

Conversational answer: I'm sorry, I couldn't find the lowest price for a chair.
```

Also not correct.

**pandas_ai.run(df, prompt='How many rows in the data?')**

```
Answer: ('Number of rows:', 21)
Conversational answer: There are 21 rows in the data.
```

It's ok, except that I except just number 21, not part of code.

**pandas_ai.run(df, prompt='How many items you have with size less than 200x200?')**

Generated:
```
filtered_df = df[(df['height'] < 200) & (df['width'] < 200)]
```

```
Answer: Number of items with size less than 200x200: 5
Conversational answer: Based on my analysis, there are a total of 5 items that have a size less than 200x200.
```

Good, but simple answer can be just "5".

**pandas_ai.run(df, prompt='What is price of chair?')**

```
Running PandasAI with openai LLM...

Code generated:

import pandas as pd

# create the dataframe
data = {'item_id': [50468953, 89326463, 50468953, 89326463, 368814],
        'name': ['BRIMNESE', 'NORDVIKEN', 'VATTVIKEN', 'FREKVENS', 'PLATSA'],
        'category': ['Beds', 'Beds', 'Bar furniture', 'Bar furniture', 'Beds'],
        'price': [2111, 265, 2111, 995, 895],
        'height': [110, 86, 105, 110, 43],
        'width': [92, 140, 51, 96, 92]}
df = pd.DataFrame(data)

# find the price of chair
chair_price = df.loc[df['category'] == 'Chairs', 'price'].values[0]
print(chair_price)

Answer: 
Conversational answer: Sure! The price of the chair is [insert price here].
```

Returns placeholder, but not answer.

**pandas_ai.run(df, prompt='How many chairs do you have?')**

```
Running PandasAI with openai LLM...

Code generated:

import pandas as pd

# create dataframe
data = {'item_id': [89326463, 49278341, 50468953, 50468953, 90420332],
        'name': ['PLATSA', 'BRIMNESE', 'VATTVIKEN', 'FREKVENS', 'NORDVIKEN'],
        'category': ['Beds', 'Beds', 'Bar furniture', 'Beds', 'Bar furniture'],
        'price': [895, 2111, 995, 995, 995],
        'height': [110, 43, 86, 99, 86],
        'width': [80, 92, 140, 92, 51]}
df = pd.DataFrame(data)

# count number of chairs
num_chairs = df[df['category'] == 'Chairs'].shape[0]

print("Number of chairs:", num_chairs)

Answer: Number of chairs: 0

Conversational answer: I'm sorry, but I don't have any chairs.
```

Hope it helps.

Thanks and waiting for next version.
Pavel

**Comment by PavelAgurov** [comment] 2023-05-17 19:05
I see new version has been released - 0.2.13

**Comment by PavelAgurov** [comment] 2023-05-17 19:19
I want to say that it's much better! All questions were answered correctly.

2 notes:

**pandas_ai.run(df, prompt='I want to buy a table')**

"Sure, let me check our inventory for tables. (Displays table inventory) I'm sorry, but we don't have any tables available at the moment."

Looks like (Displays table inventory) is excessive here.

**pandas_ai.run(df, prompt='How many chairs do you have?')**

Conversational answer: Oh, I have 5 chairs.

Why "Oh"? :)

**Comment by sandiemann** [comment] 2023-05-20 15:42
@PavelAgurov As mentioned earlier, due to the conversational flag `conversational=True`  the answer returned in a conversational way, so basically you don't get the factual response, but a more "conversational" response based on the fact. Therefore, you get an "Oh" prefix in the response.

**Comment by PavelAgurov** [comment] 2023-05-20 15:46
Sure :) In future if possible it will be good to manage how "official" this conversation. 

I would suggest to close this issue as it was originally about crash. If I will find any new problem - I will report it in next tickets. 

But problem with  (Displays table inventory) is still here.

Thanks!

**Comment by sandiemann** [comment] 2023-05-20 19:53
@PavelAgurov I cannot re-produce it,
```
pandas_ai.run(df_new, prompt='I want to buy a table')
Running PandasAI with openai LLM...
testing this error openai LLM...
Code generated:

import pandas as pd
# create dataframe
data = {'item_id': [89326463, 368814, 90420332, 50468953, 49278341],
        'name': ['NORDVIKEN', 'PLATSA', 'FREKVENS', 'BRIMNESE', 'VATTVIKEN'],
        'category': ['Bar furniture', 'Beds', 'Bar furniture', 'Beds', 'Beds'],
        'price': [895, 2111, 895, 995, 995],
        'height': [105, 105, 86, 86, 43],
        'width': [96, 140, 92, 80, 140]}
df = pd.DataFrame(data)
# filter for tables
table_df = df[df['category'] == 'Tables']
# print table options
print(table_df[['name', 'price']])

Code running:

data = {'item_id': [89326463, 368814, 90420332, 50468953, 49278341], 'name':
    ['NORDVIKEN', 'PLATSA', 'FREKVENS', 'BRIMNESE', 'VATTVIKEN'],
    'category': ['Bar furniture', 'Beds', 'Bar furniture', 'Beds', 'Beds'],
    'price': [895, 2111, 895, 995, 995], 'height': [105, 105, 86, 86, 43],
    'width': [96, 140, 92, 80, 140]}
table_df = df[df['category'] == 'Tables']
print(table_df[['name', 'price']])

Answer: Empty DataFrame
Columns: [name, price]
Index: []
Conversational answer: Sure, what kind of table are you looking for? Do you have any specific requirements or preferences in terms of size, material, or style?
Out[5]: 'Sure, what kind of table are you looking for? Do you have any specific requirements or preferences in terms of size, material, or style?'

```

@gventuri Please close this issue, as confirmed by @PavelAgurov the issue is resolved.

**Comment by PavelAgurov** [comment] 2023-05-20 21:00
@sandiemann , you are right. with version 0.2.14 it's exactly answer as you wrote above.

But as you can see - it's wrong answer, because "Answer: Empty DataFrame" - it means no table in the data.
Second point why it's wrong - there are no columns about "material, or style", so model can't ask such questions.

@gventuri , I can extract it into separated ticket as it's not about crash alredy.

**Comment by PavelAgurov** [comment] 2023-05-20 21:53
Btw - it's possible to crash library if ask some not related to the data questions. But maybe it's not a bug, but normal behaviour. I should try-catch it and answer by myself that no answer possible.

```
File D:\Anaconda3\lib\site-packages\pandasai\llm\base.py:89, in LLM._extract_code(self, response, separator)
     87 code = self._polish_code(code)
     88 if not self._is_python_code(code):
---> 89     raise NoCodeFoundError("No code found in the response")
     91 return code

NoCodeFoundError: No code found in the response
```

**Comment by gventuri** [comment] 2023-05-25 00:12
@PavelAgurov the `NoCodeFoundError: No code found in the response` is now handled, returns a conversational response.

Closing this issue as the underlying bug has been solved. Feel free to open any new issue, if you find any further bugs!

**Closed by gventuri** 2023-05-25 00:12 UTC
Labels: bug

**Comment by PavelAgurov** [comment] 2023-05-25 08:55
Thanks!
