### ISSUE TITLE
partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

### ISSUE THREAD

**Issue by AlbertoCasadoPeguero** [gventuri/pandas-ai#160] opened 2023-05-22 13:40 UTC
### 🐛 Describe the bug

when trying to import these from pandasai import PandasAI and from pandasai.llm.openai import OpenAI I get the AttributeError partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import).

**Comment by gventuri** [comment] 2023-05-22 19:47
@AlbertoCasadoPeguero thanks a lot for reporting. Which version of `PandasAI` are you currently using?
In which environment are you using it (i.e. local machine, colab, other)?

**Comment by AlbertoCasadoPeguero** [comment] 2023-05-22 20:19
Hi, i'm using version 0.2.14 of pandasai on a local Anaconda enviroment with python 3.9.16.

**Comment by gventuri** [comment] 2023-05-22 20:47
@AlbertoCasadoPeguero just tried to reproduce the same environment and have no error...

Would you mind sharing the whole script so that I can give it a try?

**Comment by AlbertoCasadoPeguero** [comment] 2023-05-22 20:58
The thing is that that's the only thing i have in my script, because i was trying the library for the first time and couldn't go pass the importing of the libraries, I even created a new enviroment on Anaconda just for that and just install pandasai so it installs all the requeriments from scratch, but since no one else had the same issue I thought that it was only me.

**Comment by sandiemann** [comment] 2023-05-23 14:55
@AlbertoCasadoPeguero since you're using conda env, check if you have `charset-normalizer` package pre-installed:
- with pip:
`pip freeze | grep charset-normalizer`
- uninstall if present (sometime this package gets installed on venv)
`pip uninstall charset-normalizer`

- installed with conda: (to check, if installed: `conda list charset-normalizer`)
`conda install -c conda-forge charset-normalizer`


hopefully, this will do the trick! let me know if it works!

**Comment by gventuri** [comment] 2023-05-24 23:06
@AlbertoCasadoPeguero did the suggestion from @sandiemann fix the issue?

**Comment by gventuri** [comment] 2023-05-27 09:29
Closing, feel free to reopen if you need further support! :)

**Closed by gventuri** 2023-05-27 09:29 UTC
Labels: bug
