### ISSUE TITLE
Using Pandas AI inside Docker Causing Permission Denied Error on Cache

### ISSUE THREAD

**Issue by BenAkko** [gventuri/pandas-ai#269] opened 2023-06-11 12:29 UTC
### 🐛 Describe the bug

Hi,

Apologies if this is an issue relating more to Docker than Pandas AI, but I have recently updated to the most recent version of Pandas AI which is now causing this error.

```
File "/usr/local/lib/python3.10/site-packages/pandasai/__init__.py", line 69, in <module>
django_1        |     class PandasAI:
django_1        |   File "/usr/local/lib/python3.10/site-packages/pandasai/__init__.py", line 117, in PandasAI
django_1        |     _cache: Cache = Cache()
django_1        |   File "/usr/local/lib/python3.10/site-packages/pandasai/helpers/cache.py", line 20, in __init__
django_1        |     os.makedirs(cache_dir)
django_1        |   File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
django_1        |     mkdir(name, mode)
django_1        | PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/site-packages/cache'
```

Is this something that I can avoid within Pandas AI, and if not, does anyone know how to configure Docker to allow Pandas AI to create this file? If this is more of an issue with Docker, please let me know and I'll close this issue.

Many thanks for any help anyone can offer!

**Comment by shankarpandala** [comment] 2023-06-12 18:35
This screwed up my demo with senior leadership 
It worked perfectly fine on local when deployed through docker this issue came up!
even after giving full permissions to '/usr/local/lib/python3.10/site-packages/cache'
it is giving different error

**Comment by BenAkko** [comment] 2023-06-12 19:22
Yes 

> Hey @BenAkko, thanks a lot for reporting. I'll look more in depth, but I expect for now you can make is work instantiating PandasAI with cache=False, like this:
> 
> ```python
> pandas_ai = PandasAI(llm, cache=False)
> ```
> 
> Please, let me know if it temporary fixes the issue!

Thanks, I'll give this a try and reply back again later. Also, thanks for making such a great package! 

I had the same situation as the other commenter, in that it worked fine locally, but in production it failed, even after I tried to give the full permissions to the folder. It may be a docker settings issue rather than a problem with Pandas AI if it works locally and fails in production?

I am using a cookiecutter-django docker template, if that is of any significance.

**Comment by shankarpandala** [comment] 2023-06-13 03:46
Cache = False didn't work as it by default cache = True getting executed at the time of import.

I am getting this error at the import itself.
Easiest fix would be to make cache as False by default in the init method.

Thanks

**Comment by vpurandara** [comment] 2023-06-15 08:47
@gventuri  when can we expect to resolve this issue

**Comment by vpurandara** [comment] 2023-06-16 06:24
with pandasai==0.5.3 not able to run the python script (not in docker) getting the following error:

```
Traceback (most recent call last):
  File "/home/purandara/Projects/pandas-ai/cacheAPI.py", line 8, in <module>
    from pandasai import PandasAI
  File "/home/purandara/anaconda3/envs/pandas-ai/lib/python3.9/site-packages/pandasai/__init__.py", line 58, in <module>
    from .llm.langchain import LangchainLLM
  File "/home/purandara/anaconda3/envs/pandas-ai/lib/python3.9/site-packages/pandasai/llm/langchain.py", line 10, in <module>
    from langchain.llms.base import LLM as LangchainBaseLLM
ModuleNotFoundError: No module named 'langchain'
```

**Comment by vpurandara** [comment] 2023-06-16 10:20
Temporarily I sorted this issue by using version==0.5.2 and  replacing the __init__.py file in Docker config: 

```
FROM python:3.9.16
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
COPY pandasai_init.py /usr/local/lib/python3.9/site-packages/pandasai/__init__.py
.
.
.
```

The updated __init__.py is saved as pandas_init.py and replace it with __init__.py

The changes I made in __init__.py are:
```
# _cache: Cache = Cache()
_enable_cache: bool = False
enable_cache=False,
if self._enable_cache:# and self._cache.get(prompt):
 # self._cache.set(prompt, code)
```

**Comment by BenAkko** [comment] 2023-06-16 13:56
> @vpurandara I've just shipped a new version that should create the folder with 777 permission. If that doesn't work either, I'd recommend you to manually create the `/cache` folder from your docker config, so that at least temporarily it fixes the issue!

Hi,

Thanks for your attempted fix, but it appears to still not resolve the bug, I'm still getting the same error as I was before. I'll try and create the folder as you suggested, and also try vpurandara's temporary fix as well.

**Comment by gventuri** [comment] 2023-06-16 22:34
Hey @BenAkko @vpurandara @shankarpandala! Should have been fixed with the release of `v0.5.5`. Please check it out and let me know. If the fix doesn't work, feel free to reopen the issue!

**Closed by gventuri** 2023-06-16 22:34 UTC
Labels: bug

**Comment by BenAkko** [comment] 2023-06-17 06:57
Hi @gventuri,

Thanks for your efforts.

Unfortunately the issue is still occurring; I'm still getting a 
```
 _gdbm.error: [Errno 11] Resource temporarily unavailable: '/app/cache/cache'
```

error when attempting to import the package. 

Also, I don't think I have the ability to reopen the issue.

**Comment by ihorizons2022** [comment] 2023-06-17 07:02
I encounter the same issue, but in different scenario : use uvicorn to open multiple workers and i believe this is related to multi threading

郭轩
15802161396
[image]
三尺剑网络科技（上海）有限公司
> From: ***@***.***>
> Date:  Sat, Jun 17, 14:58
> Subject:  Re: [gventuri/pandas-ai] Using Pandas AI inside Docker Causing Permission Denied Error on Cache (Issue #269)
> To: ***@***.***>
> Cc: ***@***.***>
> Hi @gventuri<https://github.com/gventuri>,
> Thanks for your efforts.
> Unfortunately the issue is still occurring; I'm still getting a
>  _gdbm.error: [Errno 11] Resource temporarily unavailable: '/app/cache/cache'
error when attempting to import the package.

**Comment by vpurandara** [comment] 2023-06-17 08:16
hi @gventuri , seems the issue is sorted out with v0.5.5.

Now able to run in docker container , and also tried using uvicorn multiple workers both working well.

Thanks for the efforts.

**Comment by devopssii** [comment] 2023-06-22 11:17
Name: pandasai
Version: 0.6.2
Summary: Pandas AI is a Python library that integrates generative artificial intelligence capabilities into Pandas, making dataframes conversational.
Home-page: 
Author: Gabriele Venturi
Author-email: 
License: MIT
Location: /home/myhome202323/wild/lib/python3.10/site-packages
Requires: astor, ipython, matplotlib, openai, pandas, python-dotenv
Required-by:

in this version same problem with cache, but you write that problem is gone in with v0.5.5.
i dont understand

**Comment by gventuri** [comment] 2023-06-22 13:28
@devopssii @vpurandara the issue is probably about permissions within docker.

There are 2 options:
- you can somehow enable the RW on the `cache` folder
- you run PandasAI without cache enabled, like this: `pandas_ai = PandasAI(llm, cache=False)`

This should work. Just let me know!

**Comment by devopssii** [comment] 2023-06-22 13:44
im install by pip in env docker not a problem. cache=False i allready try turning off the cache on instances and not on localhost makes pandasai useless as it uses cache for transmission

**Comment by devopssii** [comment] 2023-06-22 13:45
i use GCP

**Comment by vpurandara** [comment] 2023-06-23 05:23
@gventuri , For docker container if we run the pandas-ai first time itself in docker then  ```_gdbm.error: [Errno 11] Resource temporarily unavailable: '/app/cache/cache' ``` error is giving.

But before copying the project directory to docker image, we have to run atleast once then it will create the cache folder in local project directory and afterwards if we build the docker image and run it, no issues.

**Comment by devopssii** [comment] 2023-06-25 11:00
but if i install - pip install pandasai not in docker?

**Comment by vpurandara** [comment] 2023-06-26 11:26
we can install ```pip install pandasai``` in docker as usual. while runing pandasai, it wont create another cache folder if it already exists

**Comment by devopssii** [comment] 2023-06-26 13:18
I will write again, I do not install in docker, but simply in env. I understand that it creates a folder on installation and startup.
1. Your suggestions to add access to the folder does not work even with 777 rights, the error is the same.
2. The second option cache=False removes the error, but along with the error, the pandasai functionality itself disappears, it does not issue any responses from the dataframe after LLm processing, judging by the system files, it writes data and responses to the cache, which is forcibly turned off. The problem is not solved.
