### ISSUE TITLE
Bug https://github.com/gventuri/pandas-ai/issues/291 is still reproduced

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#524] opened 2023-09-03 15:20 UTC
### 🐛 Describe the bug

I have exactly the same problem as described in https://github.com/gventuri/pandas-ai/issues/291
It works when "enable_cache": False. Otherwise I have error on streamlit.

**Comment by sandiemann** [comment] 2023-09-03 22:07
I am facing the same issue on Mac, only able to run app with `enable_cache:False`

I believe this is happening because it is trying to access the same cache file simultaneously with other processes running & generally, shelve is not really designed for concurrent access and therefore, we need to add our additional synchronization logic. 

check the restriction:
`The [shelve](https://docs.python.org/3/library/shelve.html#module-shelve) module does not support concurrent read/write access to shelved objects. (Multiple simultaneous read accesses are safe.) When a program has a shelf open for writing, no other program should have it open for reading or writing. Unix file locking can be used to solve this, but this differs across Unix versions and requires knowledge about the database implementation used.`

https://docs.python.org/3/library/shelve.html#restrictions

We could add additional file locking mechanism to ensure that only one process can access the cache file at a time or maybe adding nested calls to `shelve.open()`  for each operation  to that the file is opened & closed properly or even better would be to introduce `sqllite` db approach for caching purpose. 

@gventuri what would you suggest? need your input

**Comment by PavelAgurov** [comment] 2023-09-04 09:06
In case of streamlit problem that folder /cache/cache is not available. Maybe it should be something like it works for charts:
```
    if save_charts_path is not None:
        charts_root_dir = save_charts_path
    else:
        # define chart save directory
        charts_root_dir = dirname(dirname(dirname(__file__)))

    chart_save_dir = os.path.join(charts_root_dir, "exports", "charts", folder_name)
```

**Comment by aiakubovich** [comment] 2023-09-08 06:12
same problem

**Comment by gventuri** [comment] 2023-09-14 22:31
Hey everyone. I've done an attempt to fix this, but being unable to reproduce it, it's very complicated for me. Could you try to update to version 1.2.2 and let me know if that works?

Thanks a lot!

**Comment by PavelAgurov** [comment] 2023-09-15 07:49
Thanks! I will check.

**Comment by PavelAgurov** [comment] 2023-09-16 17:31
@gventuri , it works now - I see it by response time. Thanks!

**Comment by gventuri** [comment] 2023-09-16 20:55
> @gventuri , it works now - I see it by response time. Thanks!

Thanks a lot for letting me know! Closing!!

**Closed** 2023-09-16 20:55 UTC
Labels: bug
